// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brifcopthszannedvrlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJyaWZjb3B0aHN6YW5uZWR2cmxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxMTQ3NzcsImV4cCI6MjA3MjY5MDc3N30.1oZcQg90CjxvkY-8uAwbE9hAOHFEajhrZukBfUlUgp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});